/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Wallet__factory } from "./Wallet__factory";
export { WalletFactory__factory } from "./WalletFactory__factory";
