/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Wallet } from "./Wallet";
export type { WalletFactory } from "./WalletFactory";
export * as factories from "./factories";
export { Wallet__factory } from "./factories/Wallet__factory";
export { WalletFactory__factory } from "./factories/WalletFactory__factory";
